### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by tracker1** [fuzzycloud/tailyew#27]
Tried to access with the latest Chrome (macOS)

Console error...
```
Failed to get subsystem status for purpose {rejected: true, message: 'UNSUPPORTED_OS'}
```

**Comment by kunjee17** [comment]
@tracker1 hey it is 2 year old code. Let me check and get back to you. I might need to update too many things.

**Comment by kunjee17** [comment]
Latest code is working. Install all the dependencies that is required to run `yew`. Install node dependencies using `npm i`. Then run demo using `npm run dev:demo` and check out this url `http://localhost:8000/#/daisyui/button` . It will show you daisy button.

**Comment by kunjee17** [comment]
Deployed version you can see here. https://fuzzycloud.github.io/tailyew/#/daisyui/button
